### PR TITLE
fixed for django 1.7

### PR DESCRIPTION
**Pull request by ppp23**
forms.util got renamed to forms.utils
not sure how to ensure backwards compatibility (check django version?)

### CODE REVIEW

**Comment by abbasovalex** [comment]
@ppp23 thank! I will add the changes

**Comment by alb3rto** [comment]
Hi, there is any plan to merge this request?

**Comment by abbasovalex** [comment]
@alb3rto hi. Could you add to top import forms.utils if django > django 1.7 and forms.util if not ?

**Comment by ppp23** [comment]
as this is still open i will take care of it one of the next days.

**Comment by abbasovalex** [comment]
It is fixed https://github.com/abbasovalex/django-SplitJSONWidget-form/commit/8129adafc617d5d966869cfd38397c9b6b08fc2d
Great thanks to @ppp23

**Pull request closed without merging**
